/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/api/v1/programs/modify": {
    /** 사업 수정 */
    put: operations["modify"];
  };
  "/api/v1/profileInventory/update/inventory": {
    /** 플레이어 인벤토리 업데이트 */
    put: operations["updateProfileInventory"];
  };
  "/api/v1/players/{id}/name": {
    /** 별명등록, 초회 이벤트 별명등록 */
    put: operations["setName"];
  };
  "/api/v1/players/getReward": {
    /** 업적 보상 획득 */
    put: operations["getRewardFromAchievement"];
  };
  "/api/v1/members/modify": {
    /** 관리자정보 수정 */
    put: operations["modify_1"];
  };
  "/api/v1/inventory/update/inventory": {
    /** 플레이어 인벤토리 업데이트 */
    put: operations["updateInventory"];
  };
  "/api/v1/schools/createSchool": {
    /** 관리자 - 학교생성 */
    post: operations["createSchool"];
  };
  "/api/v1/programs/new": {
    /** 사업 생성 */
    post: operations["batchPlayLog"];
  };
  "/api/v1/programs/delete": {
    /** 사업 삭제 */
    post: operations["delete"];
  };
  "/api/v1/profileInventory/addProfileInventory": {
    /** 아이템 구매, 획득 */
    post: operations["addProfileInventory"];
  };
  "/api/v1/playerLogs/batchPlayLog": {
    /** 게임결과 로그 일괄처리 */
    post: operations["batchPlayLog_1"];
  };
  "/api/v1/members/logout": {
    /** 로그아웃 */
    post: operations["logout"];
  };
  "/api/v1/members/login": {
    /** 로그인, accessToken, refreshToken 쿠키 생성됨 */
    post: operations["login"];
  };
  "/api/v1/members/admin/login": {
    /** 관리자 로그인, accessToken, refreshToken 쿠키 생성됨 */
    post: operations["adminLogin"];
  };
  "/api/v1/members/admin/checkPassword": {
    /** 관리자 비밀번호 확인 */
    post: operations["adminCheckPassword"];
  };
  "/api/v1/inventory/addInventory": {
    /** 아이템 구매, 획득 */
    post: operations["addInventory"];
  };
  "/api/v1/gameMaps/gameMap/test2": {
    /** 특정 게임 테스트용2 */
    post: operations["getGameMapTest2"];
  };
  "/api/v1/gameLogs/batchGameLog": {
    /** 게임 로그 일괄 처리 */
    post: operations["batchPlayLog_2"];
  };
  "/api/v1/test/test": {
    /** 플레이어 인벤토리 조회 */
    get: operations["test"];
  };
  "/api/v1/schools": {
    /** 학교 전체 조회 */
    get: operations["getSchools"];
  };
  "/api/v1/regions": {
    /** 시도 조회 */
    get: operations["getRegions"];
  };
  "/api/v1/programs": {
    /** 사업 조회 */
    get: operations["getPrograms"];
  };
  "/api/v1/programs/{id}": {
    /** 사업 단건 조회 */
    get: operations["getProgram"];
  };
  "/api/v1/profileInventory/myInventory": {
    /** 플레이어 인벤토리 조회 */
    get: operations["getMyInventory"];
  };
  "/api/v1/profile/profiles": {
    /** 전체 상점 프로필아이콘 목록 조회 */
    get: operations["getProfiles"];
  };
  "/api/v1/profile/all": {
    /** 전체 프로필아이콘 목록 조회 */
    get: operations["getAllProfile"];
  };
  "/api/v1/playerLogs/highest": {
    /** 플레이어의 최고기록 로그 */
    get: operations["getHighestLog"];
  };
  "/api/v1/playerLogs/gamesLastLog/{gameMapId}": {
    /** 해당 게임의 마지막 로그 */
    get: operations["getGamesLastLog"];
  };
  "/api/v1/playerLogs/clearLog/{stage}": {
    /** 스테이지 클리어 로그 */
    get: operations["getClearLog"];
  };
  "/api/v1/members/program": {
    /** 사업관리자 이상 조회 */
    get: operations["getSchools_1"];
  };
  "/api/v1/members/me": {
    /** 내 정보 */
    get: operations["getMe"];
  };
  "/api/v1/members/adm/me": {
    /** 관리자 마이페이지 */
    get: operations["getAdminMe"];
  };
  "/api/v1/logs/profile": {
    /** 학습정보 로그정보 조회 */
    get: operations["getProfileMainLog"];
  };
  "/api/v1/logs/detail": {
    /** 학습정보 스테이지 상세로그 조회 */
    get: operations["getProfileDetailLog"];
  };
  "/api/v1/item/items": {
    /** 전체 아이템 목록 조회 */
    get: operations["getItems"];
  };
  "/api/v1/inventory/myInventory": {
    /** 플레이어 인벤토리 조회 */
    get: operations["getMyInventory_1"];
  };
  "/api/v1/gameMaps/gameMap/{stage}/{id}": {
    /** 특정 게임 맵 조회와 자격검증 */
    get: operations["getGameMap"];
  };
  "/api/v1/gameMaps/gameMap/{id}": {
    /** 특정 게임 맵 과 필요장비 조회 */
    get: operations["getGameMapWithItem"];
  };
  "/api/v1/gameMaps/gameMap/test/{gameInfo}": {
    /** 특정 게임 테스트용 */
    get: operations["getGameMapTest"];
  };
  "/api/v1/ads": {
    /** 행정구역 조회 */
    get: operations["getAds"];
  };
  "/api/v1/achievements": {
    /** 업적 목록 조회 */
    get: operations["getAchievements"];
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    Empty: Record<string, never>;
    RsDataEmpty: {
      resultCode: string;
      /** Format: int32 */
      statusCode: number;
      msg: string;
      data: components["schemas"]["Empty"];
    };
    MemberInputListDto: {
      /** Format: int64 */
      id?: number;
      username?: string;
      name?: string;
    };
    ModifyProgramRequestBody: {
      /** Format: int64 */
      id: number;
      name: string;
      /** Format: date */
      startDate: string;
      /** Format: date */
      endDate: string;
      region: string;
      ad: string;
      agency: components["schemas"]["SchoolInputListDto"][];
      member: components["schemas"]["MemberInputListDto"][];
    };
    SchoolInputListDto: {
      /** Format: int64 */
      id?: number;
      region?: string;
      administrativeDistrict?: string;
      schoolName?: string;
    };
    ModifyProgramResponseBody: {
      programDto: components["schemas"]["ProgramDto"];
    };
    ProgramDto: {
      /** Format: int64 */
      id: number;
      /** Format: date-time */
      createDate: string;
      /** Format: date-time */
      modifyDate: string;
      name: string;
      /** Format: date */
      startDate: string;
      /** Format: date */
      endDate: string;
      city: string;
      administrativeDistrict: string;
      responsibleMemberNames: string[];
      schoolsNames: string[];
    };
    RsDataModifyProgramResponseBody: {
      resultCode: string;
      /** Format: int32 */
      statusCode: number;
      msg: string;
      data: components["schemas"]["ModifyProgramResponseBody"];
    };
    AchievementDto: {
      /** Format: int64 */
      id: number;
      /** Format: date-time */
      createDate: string;
      name: string;
      description: string;
      /** Format: int32 */
      rewardExp: number;
      /** Format: int32 */
      rewardJewel: number;
      rewardIconSource?: string;
      /** Format: int32 */
      getReward?: number;
      /** Format: int32 */
      isAchieved?: number;
    };
    ProfileDto: {
      /** Format: int64 */
      id: number;
      /** Format: date-time */
      createDate: string;
      /** Format: date-time */
      updateDate: string;
      name: string;
      description: string;
      sourcePath: string;
      /** Format: int32 */
      price: number;
      achievement?: components["schemas"]["AchievementDto"];
    };
    ProfileInventoryDto: {
      /** Format: int64 */
      id: number;
      /** Format: date-time */
      createDate: string;
      /** Format: date-time */
      updateDate: string;
      profileIcon: components["schemas"]["ProfileDto"];
      isEquipped: boolean;
    };
    UpdateProfileInventoryRequestBody: {
      profileInventoryDtoList: components["schemas"]["ProfileInventoryDto"][];
    };
    MemberDto: {
      /** Format: int64 */
      id: number;
      /** Format: date-time */
      createDate: string;
      /** Format: date-time */
      modifyDate: string;
      username: string;
      name: string;
      cellphoneNo: string;
      authorities: string[];
      player: components["schemas"]["PlayerDto"];
    };
    PlayerDto: {
      /** Format: int64 */
      id: number;
      /** Format: date-time */
      createDate: string;
      /** Format: date-time */
      modifyDate: string;
      nickname: string;
      /** Format: int32 */
      exp: number;
      /** Format: int32 */
      gems: number;
      /** Format: int32 */
      characterType: number;
      /** Format: int32 */
      backgroundVolume: number;
      /** Format: int32 */
      effectVolume: number;
      /** Format: int32 */
      editorAutoComplete: number;
      /** Format: int32 */
      editorAutoClose: number;
    };
    RsDataUpdateProfileInventoryResponseBody: {
      resultCode: string;
      /** Format: int32 */
      statusCode: number;
      msg: string;
      data: components["schemas"]["UpdateProfileInventoryResponseBody"];
    };
    UpdateProfileInventoryResponseBody: {
      memberDto: components["schemas"]["MemberDto"];
    };
    SetNickNameRequestBody: {
      nickname: string;
      /** Format: int32 */
      characterType: number;
    };
    RsDataSetNickNameResponseBody: {
      resultCode: string;
      /** Format: int32 */
      statusCode: number;
      msg: string;
      data: components["schemas"]["SetNickNameResponseBody"];
    };
    SetNickNameResponseBody: {
      item: components["schemas"]["PlayerDto"];
    };
    GetRewardFromAchievementRequestBody: {
      achievement: components["schemas"]["AchievementDto"];
    };
    ModifyRequestBody: {
      newPassword?: string;
      realName: string;
      cellphoneNo: string;
      department: string;
      position: string;
      extensionNo: string;
    };
    ModifyResponseBody: {
      item: components["schemas"]["MemberDto"];
    };
    RsDataModifyResponseBody: {
      resultCode: string;
      /** Format: int32 */
      statusCode: number;
      msg: string;
      data: components["schemas"]["ModifyResponseBody"];
    };
    InventoryDto: {
      /** Format: int64 */
      id: number;
      /** Format: date-time */
      createDate: string;
      /** Format: date-time */
      updateDate: string;
      item: components["schemas"]["ItemDto"];
      isEquipped: boolean;
    };
    ItemDto: {
      /** Format: int64 */
      id: number;
      /** Format: date-time */
      createDate: string;
      /** Format: date-time */
      updateDate: string;
      /** Format: int64 */
      itemPartsId: number;
      name: string;
      /** Format: int32 */
      price: number;
      description: string;
      availableCommands: string;
      sourcePath: string;
    };
    UpdateInventoryRequestBody: {
      inventoryList: components["schemas"]["InventoryDto"][];
    };
    RsDataUpdateInventoryResponseBody: {
      resultCode: string;
      /** Format: int32 */
      statusCode: number;
      msg: string;
      data: components["schemas"]["UpdateInventoryResponseBody"];
    };
    UpdateInventoryResponseBody: {
      memberDto: components["schemas"]["MemberDto"];
    };
    CreateSchoolRequestBody: {
      region?: string;
      administrativeDistrict?: string;
      schoolLevel?: string;
      highSchoolType?: string;
      schoolName?: string;
      establishmentType?: string;
      coeducationType?: string;
      areaType?: string;
      address?: string;
      phoneNumber?: string;
    };
    CreateSchoolResponseBody: {
      schoolDto?: components["schemas"]["SchoolDto"];
    };
    RsDataCreateSchoolResponseBody: {
      resultCode: string;
      /** Format: int32 */
      statusCode: number;
      msg: string;
      data: components["schemas"]["CreateSchoolResponseBody"];
    };
    SchoolDto: {
      /** Format: int64 */
      id?: number;
      region?: string;
      administrativeDistrict?: string;
      schoolLevel?: string;
      highSchoolType?: string;
      schoolName?: string;
      establishmentType?: string;
      coeducationType?: string;
      areaType?: string;
      address?: string;
      phoneNumber?: string;
    };
    createProgramRequestBody: {
      name: string;
      /** Format: date */
      startDate: string;
      /** Format: date */
      endDate: string;
      region: string;
      ad: string;
      agency: components["schemas"]["SchoolInputListDto"][];
      member: components["schemas"]["MemberInputListDto"][];
    };
    RsDataCreateProgramResponseBody: {
      resultCode: string;
      /** Format: int32 */
      statusCode: number;
      msg: string;
      data: components["schemas"]["createProgramResponseBody"];
    };
    createProgramResponseBody: {
      program: components["schemas"]["ProgramDto"];
    };
    ProgramDeleteRequestBody: {
      programIds: number[];
    };
    addProfileInventoryRequestBody: {
      /** Format: int64 */
      profileId: number;
    };
    RsDataAddProfileInventoryResponseBody: {
      resultCode: string;
      /** Format: int32 */
      statusCode: number;
      msg: string;
      data: components["schemas"]["addProfileInventoryResponseBody"];
    };
    addProfileInventoryResponseBody: {
      profileInventoryDto: components["schemas"]["ProfileInventoryDto"];
    };
    BatchPlayLogRequestBody: {
      gameMapDto: components["schemas"]["GameMapDto"];
      result: string;
    };
    GameMapDto: {
      /** Format: int64 */
      id: number;
      /** Format: date-time */
      createDate: string;
      /** Format: date-time */
      modifyDate: string;
      stage: string;
      step: string;
      difficulty: string;
      /** Format: int32 */
      level: number;
      editorAutoComplete: string;
      editorMessage: string;
      clearGoal: string;
      cocosInfo: string;
      guideText: string;
      guideImage: string;
      commandGuide: string;
      /** Format: int32 */
      rewardExp: number;
      /** Format: int32 */
      rewardJewel: number;
      rewardItem?: components["schemas"]["ItemDto"];
    };
    LoginRequestBody: {
      /** Format: int32 */
      roleLevel: number;
      username: string;
      password: string;
    };
    LoginResponseBody: {
      item: components["schemas"]["MemberDto"];
    };
    RsDataLoginResponseBody: {
      resultCode: string;
      /** Format: int32 */
      statusCode: number;
      msg: string;
      data: components["schemas"]["LoginResponseBody"];
    };
    AdminLoginRequestBody: {
      username: string;
      password: string;
    };
    AdminCheckPasswordRequestBody: {
      password: string;
    };
    addInventoryRequestBody: {
      /** Format: int64 */
      itemId: number;
    };
    RsDataAddInventoryResponseBody: {
      resultCode: string;
      /** Format: int32 */
      statusCode: number;
      msg: string;
      data: components["schemas"]["addInventoryResponseBody"];
    };
    addInventoryResponseBody: {
      inventoryDto: components["schemas"]["InventoryDto"];
    };
    GameMapTest2RequestBody: {
      gameInfo: string;
      editorValue: string;
    };
    RsDataObject: {
      resultCode: string;
      /** Format: int32 */
      statusCode: number;
      msg: string;
      data: Record<string, never>;
    };
    BatchGameLogRequestBody: {
      gameMapDto: components["schemas"]["GameMapDto"];
      /** Format: int32 */
      result: number;
      /** Format: int32 */
      editorAutoComplete: number;
      /** Format: int32 */
      editorAutoClose: number;
      /** Format: int32 */
      killCount: number;
    };
    RsDataTestResponseBody: {
      resultCode: string;
      /** Format: int32 */
      statusCode: number;
      msg: string;
      data: components["schemas"]["TestResponseBody"];
    };
    TestResponseBody: {
      /** Format: int64 */
      id: number;
    };
    RsDataSchoolsResponseBody: {
      resultCode: string;
      /** Format: int32 */
      statusCode: number;
      msg: string;
      data: components["schemas"]["SchoolsResponseBody"];
    };
    SchoolsResponseBody: {
      schools?: components["schemas"]["SchoolInputListDto"][];
    };
    Region: {
      /** Format: int64 */
      code?: number;
      name?: string;
    };
    RegionsResponseBody: {
      regions?: components["schemas"]["Region"][];
    };
    RsDataRegionsResponseBody: {
      resultCode: string;
      /** Format: int32 */
      statusCode: number;
      msg: string;
      data: components["schemas"]["RegionsResponseBody"];
    };
    GetProgramsResponseBody: {
      itemPage: components["schemas"]["PageDtoProgramDto"];
    };
    PageDtoProgramDto: {
      /** Format: int64 */
      totalElementsCount: number;
      /** Format: int64 */
      pageElementsCount: number;
      /** Format: int64 */
      totalPagesCount: number;
      /** Format: int32 */
      number: number;
      content: components["schemas"]["ProgramDto"][];
    };
    RsDataGetProgramsResponseBody: {
      resultCode: string;
      /** Format: int32 */
      statusCode: number;
      msg: string;
      data: components["schemas"]["GetProgramsResponseBody"];
    };
    GetProgramResponseBody: {
      item: components["schemas"]["ProgramDetailDto"];
    };
    ProgramDetailDto: {
      /** Format: int64 */
      id: number;
      /** Format: date-time */
      createDate: string;
      /** Format: date-time */
      modifyDate: string;
      name: string;
      /** Format: date */
      startDate: string;
      /** Format: date */
      endDate: string;
      city: string;
      administrativeDistrict: string;
      responsibleMemberNames: components["schemas"]["MemberInputListDto"][];
      schoolsNames: components["schemas"]["SchoolInputListDto"][];
    };
    RsDataGetProgramResponseBody: {
      resultCode: string;
      /** Format: int32 */
      statusCode: number;
      msg: string;
      data: components["schemas"]["GetProgramResponseBody"];
    };
    MyProfileInventoryResponseBody: {
      profileInventoryDtoList: components["schemas"]["ProfileInventoryDto"][];
    };
    RsDataMyProfileInventoryResponseBody: {
      resultCode: string;
      /** Format: int32 */
      statusCode: number;
      msg: string;
      data: components["schemas"]["MyProfileInventoryResponseBody"];
    };
    ProfilesResponseBody: {
      profileDtoList: components["schemas"]["ProfileDto"][];
    };
    RsDataProfilesResponseBody: {
      resultCode: string;
      /** Format: int32 */
      statusCode: number;
      msg: string;
      data: components["schemas"]["ProfilesResponseBody"];
    };
    GetAllProfileResponseBody: {
      profileDtoList: components["schemas"]["ProfileDto"][];
    };
    RsDataGetAllProfileResponseBody: {
      resultCode: string;
      /** Format: int32 */
      statusCode: number;
      msg: string;
      data: components["schemas"]["GetAllProfileResponseBody"];
    };
    GamesHighestLogResponseBody: {
      playerLogDto?: components["schemas"]["PlayerLogDto"];
    };
    PlayerLogDto: {
      /** Format: int64 */
      id: number;
      /** Format: date-time */
      createDate: string;
      /** Format: date-time */
      modifyDate: string;
      logType: string;
      username: string;
      /** Format: int64 */
      gameMapId: number;
      gameMapStage: string;
      gameMapStep: string;
      gameMapDifficulty: string;
      /** Format: int32 */
      gameMapLevel: number;
      detailText?: string;
      /** Format: int32 */
      detailInt?: number;
    };
    RsDataGamesHighestLogResponseBody: {
      resultCode: string;
      /** Format: int32 */
      statusCode: number;
      msg: string;
      data: components["schemas"]["GamesHighestLogResponseBody"];
    };
    GamesLastLogResponseBody: {
      playerLogDto?: components["schemas"]["PlayerLogDto"];
    };
    RsDataGamesLastLogResponseBody: {
      resultCode: string;
      /** Format: int32 */
      statusCode: number;
      msg: string;
      data: components["schemas"]["GamesLastLogResponseBody"];
    };
    ClearLogResponseBody: {
      playerLogDtoList: components["schemas"]["PlayerLogDto"][];
    };
    RsDataClearLogResponseBody: {
      resultCode: string;
      /** Format: int32 */
      statusCode: number;
      msg: string;
      data: components["schemas"]["ClearLogResponseBody"];
    };
    ProgramMembersResponseBody: {
      members?: components["schemas"]["MemberInputListDto"][];
    };
    RsDataProgramMembersResponseBody: {
      resultCode: string;
      /** Format: int32 */
      statusCode: number;
      msg: string;
      data: components["schemas"]["ProgramMembersResponseBody"];
    };
    MeResponseBody: {
      item: components["schemas"]["MemberDto"];
    };
    RsDataMeResponseBody: {
      resultCode: string;
      /** Format: int32 */
      statusCode: number;
      msg: string;
      data: components["schemas"]["MeResponseBody"];
    };
    AdminMeResponseBody: {
      item: components["schemas"]["MemberProgramAdmDto"];
    };
    MemberProgramAdmDto: {
      /** Format: int64 */
      id: number;
      /** Format: date-time */
      createDate: string;
      /** Format: date-time */
      modifyDate: string;
      username: string;
      name: string;
      cellphoneNo: string;
      authorities: string[];
      department: string;
      position: string;
      extensionNo: string;
      responsibilities: components["schemas"]["ProgramDto"][];
    };
    RsDataAdminMeResponseBody: {
      resultCode: string;
      /** Format: int32 */
      statusCode: number;
      msg: string;
      data: components["schemas"]["AdminMeResponseBody"];
    };
    GetProfileLogResponseBody: {
      profileLogDto: components["schemas"]["ProfileLogDto"];
    };
    ProfileClearRateDto: {
      difficulty: string;
      /** Format: int64 */
      clearCount: number;
    };
    ProfileLogDto: {
      playerLogDto?: components["schemas"]["PlayerLogDto"];
      profileClearRateDtoList: components["schemas"]["ProfileClearRateDto"][];
    };
    RsDataGetProfileLogResponseBody: {
      resultCode: string;
      /** Format: int32 */
      statusCode: number;
      msg: string;
      data: components["schemas"]["GetProfileLogResponseBody"];
    };
    GetDetailLogResponseBody: {
      profileDetailLogDto: components["schemas"]["ProfileDetailLogDto"];
    };
    ProfileDetailLogDto: {
      /** Format: int64 */
      clearCount: number;
      /** Format: int64 */
      executionCount: number;
    };
    RsDataGetDetailLogResponseBody: {
      resultCode: string;
      /** Format: int32 */
      statusCode: number;
      msg: string;
      data: components["schemas"]["GetDetailLogResponseBody"];
    };
    ItemsResponseBody: {
      itemDtoList: components["schemas"]["ItemDto"][];
    };
    RsDataItemsResponseBody: {
      resultCode: string;
      /** Format: int32 */
      statusCode: number;
      msg: string;
      data: components["schemas"]["ItemsResponseBody"];
    };
    MyInventoryResponseBody: {
      inventoryDto: components["schemas"]["InventoryDto"][];
    };
    RsDataMyInventoryResponseBody: {
      resultCode: string;
      /** Format: int32 */
      statusCode: number;
      msg: string;
      data: components["schemas"]["MyInventoryResponseBody"];
    };
    GameMapResponseBody: {
      gameMapDto?: components["schemas"]["GameMapDto"];
    };
    RsDataGameMapResponseBody: {
      resultCode: string;
      /** Format: int32 */
      statusCode: number;
      msg: string;
      data: components["schemas"]["GameMapResponseBody"];
    };
    GameMapResponseBodyWithRequireItem: {
      gameMapDto: components["schemas"]["GameMapDto"];
      requirePartsDto: components["schemas"]["RequirePartsDto"][];
    };
    RequirePartsDto: {
      /** Format: int64 */
      id: number;
      /** Format: int64 */
      itemPartsId: number;
    };
    RsDataGameMapResponseBodyWithRequireItem: {
      resultCode: string;
      /** Format: int32 */
      statusCode: number;
      msg: string;
      data: components["schemas"]["GameMapResponseBodyWithRequireItem"];
    };
    GameMapTestResponseBody: {
      gameMapDto?: components["schemas"]["GameMapDto"];
    };
    RsDataGameMapTestResponseBody: {
      resultCode: string;
      /** Format: int32 */
      statusCode: number;
      msg: string;
      data: components["schemas"]["GameMapTestResponseBody"];
    };
    AdministrativeDistrict: {
      /** Format: int64 */
      code?: number;
      name?: string;
      /** Format: int64 */
      regionCode?: number;
    };
    AdsResponseBody: {
      ads?: components["schemas"]["AdministrativeDistrict"][];
    };
    RsDataAdsResponseBody: {
      resultCode: string;
      /** Format: int32 */
      statusCode: number;
      msg: string;
      data: components["schemas"]["AdsResponseBody"];
    };
    GetAchievementResponseBody: {
      achievementDtoList: components["schemas"]["AchievementDto"][];
    };
    RsDataGetAchievementResponseBody: {
      resultCode: string;
      /** Format: int32 */
      statusCode: number;
      msg: string;
      data: components["schemas"]["GetAchievementResponseBody"];
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export interface operations {

  /** 사업 수정 */
  modify: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["ModifyProgramRequestBody"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "application/json": components["schemas"]["RsDataModifyProgramResponseBody"];
        };
      };
      /** @description Bad Request */
      400: {
        content: {
          "application/json": components["schemas"]["RsDataEmpty"];
        };
      };
    };
  };
  /** 플레이어 인벤토리 업데이트 */
  updateProfileInventory: {
    requestBody: {
      content: {
        "*/*": components["schemas"]["UpdateProfileInventoryRequestBody"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "application/json": components["schemas"]["RsDataUpdateProfileInventoryResponseBody"];
        };
      };
      /** @description Bad Request */
      400: {
        content: {
          "application/json": components["schemas"]["RsDataEmpty"];
        };
      };
    };
  };
  /** 별명등록, 초회 이벤트 별명등록 */
  setName: {
    parameters: {
      path: {
        id: number;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["SetNickNameRequestBody"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "application/json": components["schemas"]["RsDataSetNickNameResponseBody"];
        };
      };
      /** @description Bad Request */
      400: {
        content: {
          "application/json": components["schemas"]["RsDataEmpty"];
        };
      };
    };
  };
  /** 업적 보상 획득 */
  getRewardFromAchievement: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["GetRewardFromAchievementRequestBody"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: never;
      };
      /** @description Bad Request */
      400: {
        content: {
          "application/json": components["schemas"]["RsDataEmpty"];
        };
      };
    };
  };
  /** 관리자정보 수정 */
  modify_1: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["ModifyRequestBody"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "application/json": components["schemas"]["RsDataModifyResponseBody"];
        };
      };
      /** @description Bad Request */
      400: {
        content: {
          "application/json": components["schemas"]["RsDataEmpty"];
        };
      };
    };
  };
  /** 플레이어 인벤토리 업데이트 */
  updateInventory: {
    requestBody: {
      content: {
        "*/*": components["schemas"]["UpdateInventoryRequestBody"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "application/json": components["schemas"]["RsDataUpdateInventoryResponseBody"];
        };
      };
      /** @description Bad Request */
      400: {
        content: {
          "application/json": components["schemas"]["RsDataEmpty"];
        };
      };
    };
  };
  /** 관리자 - 학교생성 */
  createSchool: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateSchoolRequestBody"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "application/json": components["schemas"]["RsDataCreateSchoolResponseBody"];
        };
      };
      /** @description Bad Request */
      400: {
        content: {
          "application/json": components["schemas"]["RsDataEmpty"];
        };
      };
    };
  };
  /** 사업 생성 */
  batchPlayLog: {
    requestBody: {
      content: {
        "*/*": components["schemas"]["createProgramRequestBody"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "application/json": components["schemas"]["RsDataCreateProgramResponseBody"];
        };
      };
      /** @description Bad Request */
      400: {
        content: {
          "application/json": components["schemas"]["RsDataEmpty"];
        };
      };
    };
  };
  /** 사업 삭제 */
  delete: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["ProgramDeleteRequestBody"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "application/json": components["schemas"]["RsDataEmpty"];
        };
      };
      /** @description Bad Request */
      400: {
        content: {
          "application/json": components["schemas"]["RsDataEmpty"];
        };
      };
    };
  };
  /** 아이템 구매, 획득 */
  addProfileInventory: {
    requestBody: {
      content: {
        "*/*": components["schemas"]["addProfileInventoryRequestBody"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "application/json": components["schemas"]["RsDataAddProfileInventoryResponseBody"];
        };
      };
      /** @description Bad Request */
      400: {
        content: {
          "application/json": components["schemas"]["RsDataEmpty"];
        };
      };
    };
  };
  /** 게임결과 로그 일괄처리 */
  batchPlayLog_1: {
    requestBody: {
      content: {
        "*/*": components["schemas"]["BatchPlayLogRequestBody"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: never;
      };
      /** @description Bad Request */
      400: {
        content: {
          "application/json": components["schemas"]["RsDataEmpty"];
        };
      };
    };
  };
  /** 로그아웃 */
  logout: {
    responses: {
      /** @description OK */
      200: {
        content: {
          "application/json": components["schemas"]["RsDataEmpty"];
        };
      };
      /** @description Bad Request */
      400: {
        content: {
          "application/json": components["schemas"]["RsDataEmpty"];
        };
      };
    };
  };
  /** 로그인, accessToken, refreshToken 쿠키 생성됨 */
  login: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["LoginRequestBody"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "application/json": components["schemas"]["RsDataLoginResponseBody"];
        };
      };
      /** @description Bad Request */
      400: {
        content: {
          "application/json": components["schemas"]["RsDataEmpty"];
        };
      };
    };
  };
  /** 관리자 로그인, accessToken, refreshToken 쿠키 생성됨 */
  adminLogin: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["AdminLoginRequestBody"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "application/json": components["schemas"]["RsDataLoginResponseBody"];
        };
      };
      /** @description Bad Request */
      400: {
        content: {
          "application/json": components["schemas"]["RsDataEmpty"];
        };
      };
    };
  };
  /** 관리자 비밀번호 확인 */
  adminCheckPassword: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["AdminCheckPasswordRequestBody"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "application/json": components["schemas"]["RsDataLoginResponseBody"];
        };
      };
      /** @description Bad Request */
      400: {
        content: {
          "application/json": components["schemas"]["RsDataEmpty"];
        };
      };
    };
  };
  /** 아이템 구매, 획득 */
  addInventory: {
    requestBody: {
      content: {
        "*/*": components["schemas"]["addInventoryRequestBody"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "application/json": components["schemas"]["RsDataAddInventoryResponseBody"];
        };
      };
      /** @description Bad Request */
      400: {
        content: {
          "application/json": components["schemas"]["RsDataEmpty"];
        };
      };
    };
  };
  /** 특정 게임 테스트용2 */
  getGameMapTest2: {
    requestBody: {
      content: {
        "*/*": components["schemas"]["GameMapTest2RequestBody"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "application/json": components["schemas"]["RsDataObject"];
        };
      };
      /** @description Bad Request */
      400: {
        content: {
          "application/json": components["schemas"]["RsDataEmpty"];
        };
      };
    };
  };
  /** 게임 로그 일괄 처리 */
  batchPlayLog_2: {
    requestBody: {
      content: {
        "*/*": components["schemas"]["BatchGameLogRequestBody"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: never;
      };
      /** @description Bad Request */
      400: {
        content: {
          "application/json": components["schemas"]["RsDataEmpty"];
        };
      };
    };
  };
  /** 플레이어 인벤토리 조회 */
  test: {
    responses: {
      /** @description OK */
      200: {
        content: {
          "application/json": components["schemas"]["RsDataTestResponseBody"];
        };
      };
      /** @description Bad Request */
      400: {
        content: {
          "application/json": components["schemas"]["RsDataEmpty"];
        };
      };
    };
  };
  /** 학교 전체 조회 */
  getSchools: {
    responses: {
      /** @description OK */
      200: {
        content: {
          "application/json": components["schemas"]["RsDataSchoolsResponseBody"];
        };
      };
      /** @description Bad Request */
      400: {
        content: {
          "application/json": components["schemas"]["RsDataEmpty"];
        };
      };
    };
  };
  /** 시도 조회 */
  getRegions: {
    responses: {
      /** @description OK */
      200: {
        content: {
          "application/json": components["schemas"]["RsDataRegionsResponseBody"];
        };
      };
      /** @description Bad Request */
      400: {
        content: {
          "application/json": components["schemas"]["RsDataEmpty"];
        };
      };
    };
  };
  /** 사업 조회 */
  getPrograms: {
    parameters: {
      query?: {
        page?: number;
        kw?: string;
        kwType?: "ALL" | "TITLE" | "REGION" | "INCHARGENAME" | "AGENCY";
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "application/json": components["schemas"]["RsDataGetProgramsResponseBody"];
        };
      };
      /** @description Bad Request */
      400: {
        content: {
          "application/json": components["schemas"]["RsDataEmpty"];
        };
      };
    };
  };
  /** 사업 단건 조회 */
  getProgram: {
    parameters: {
      path: {
        id: number;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "application/json": components["schemas"]["RsDataGetProgramResponseBody"];
        };
      };
      /** @description Bad Request */
      400: {
        content: {
          "application/json": components["schemas"]["RsDataEmpty"];
        };
      };
    };
  };
  /** 플레이어 인벤토리 조회 */
  getMyInventory: {
    responses: {
      /** @description OK */
      200: {
        content: {
          "application/json": components["schemas"]["RsDataMyProfileInventoryResponseBody"];
        };
      };
      /** @description Bad Request */
      400: {
        content: {
          "application/json": components["schemas"]["RsDataEmpty"];
        };
      };
    };
  };
  /** 전체 상점 프로필아이콘 목록 조회 */
  getProfiles: {
    responses: {
      /** @description OK */
      200: {
        content: {
          "application/json": components["schemas"]["RsDataProfilesResponseBody"];
        };
      };
      /** @description Bad Request */
      400: {
        content: {
          "application/json": components["schemas"]["RsDataEmpty"];
        };
      };
    };
  };
  /** 전체 프로필아이콘 목록 조회 */
  getAllProfile: {
    responses: {
      /** @description OK */
      200: {
        content: {
          "application/json": components["schemas"]["RsDataGetAllProfileResponseBody"];
        };
      };
      /** @description Bad Request */
      400: {
        content: {
          "application/json": components["schemas"]["RsDataEmpty"];
        };
      };
    };
  };
  /** 플레이어의 최고기록 로그 */
  getHighestLog: {
    responses: {
      /** @description OK */
      200: {
        content: {
          "application/json": components["schemas"]["RsDataGamesHighestLogResponseBody"];
        };
      };
      /** @description Bad Request */
      400: {
        content: {
          "application/json": components["schemas"]["RsDataEmpty"];
        };
      };
    };
  };
  /** 해당 게임의 마지막 로그 */
  getGamesLastLog: {
    parameters: {
      path: {
        gameMapId: number;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "application/json": components["schemas"]["RsDataGamesLastLogResponseBody"];
        };
      };
      /** @description Bad Request */
      400: {
        content: {
          "application/json": components["schemas"]["RsDataEmpty"];
        };
      };
    };
  };
  /** 스테이지 클리어 로그 */
  getClearLog: {
    parameters: {
      path: {
        stage: string;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "application/json": components["schemas"]["RsDataClearLogResponseBody"];
        };
      };
      /** @description Bad Request */
      400: {
        content: {
          "application/json": components["schemas"]["RsDataEmpty"];
        };
      };
    };
  };
  /** 사업관리자 이상 조회 */
  getSchools_1: {
    responses: {
      /** @description OK */
      200: {
        content: {
          "application/json": components["schemas"]["RsDataProgramMembersResponseBody"];
        };
      };
      /** @description Bad Request */
      400: {
        content: {
          "application/json": components["schemas"]["RsDataEmpty"];
        };
      };
    };
  };
  /** 내 정보 */
  getMe: {
    responses: {
      /** @description OK */
      200: {
        content: {
          "application/json": components["schemas"]["RsDataMeResponseBody"];
        };
      };
      /** @description Bad Request */
      400: {
        content: {
          "application/json": components["schemas"]["RsDataEmpty"];
        };
      };
    };
  };
  /** 관리자 마이페이지 */
  getAdminMe: {
    responses: {
      /** @description OK */
      200: {
        content: {
          "application/json": components["schemas"]["RsDataAdminMeResponseBody"];
        };
      };
      /** @description Bad Request */
      400: {
        content: {
          "application/json": components["schemas"]["RsDataEmpty"];
        };
      };
    };
  };
  /** 학습정보 로그정보 조회 */
  getProfileMainLog: {
    responses: {
      /** @description OK */
      200: {
        content: {
          "application/json": components["schemas"]["RsDataGetProfileLogResponseBody"];
        };
      };
      /** @description Bad Request */
      400: {
        content: {
          "application/json": components["schemas"]["RsDataEmpty"];
        };
      };
    };
  };
  /** 학습정보 스테이지 상세로그 조회 */
  getProfileDetailLog: {
    parameters: {
      query: {
        diff: string;
        step: string;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "application/json": components["schemas"]["RsDataGetDetailLogResponseBody"];
        };
      };
      /** @description Bad Request */
      400: {
        content: {
          "application/json": components["schemas"]["RsDataEmpty"];
        };
      };
    };
  };
  /** 전체 아이템 목록 조회 */
  getItems: {
    responses: {
      /** @description OK */
      200: {
        content: {
          "application/json": components["schemas"]["RsDataItemsResponseBody"];
        };
      };
      /** @description Bad Request */
      400: {
        content: {
          "application/json": components["schemas"]["RsDataEmpty"];
        };
      };
    };
  };
  /** 플레이어 인벤토리 조회 */
  getMyInventory_1: {
    responses: {
      /** @description OK */
      200: {
        content: {
          "application/json": components["schemas"]["RsDataMyInventoryResponseBody"];
        };
      };
      /** @description Bad Request */
      400: {
        content: {
          "application/json": components["schemas"]["RsDataEmpty"];
        };
      };
    };
  };
  /** 특정 게임 맵 조회와 자격검증 */
  getGameMap: {
    parameters: {
      path: {
        stage: string;
        id: number;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "application/json": components["schemas"]["RsDataGameMapResponseBody"];
        };
      };
      /** @description Bad Request */
      400: {
        content: {
          "application/json": components["schemas"]["RsDataEmpty"];
        };
      };
    };
  };
  /** 특정 게임 맵 과 필요장비 조회 */
  getGameMapWithItem: {
    parameters: {
      path: {
        id: number;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "application/json": components["schemas"]["RsDataGameMapResponseBodyWithRequireItem"];
        };
      };
      /** @description Bad Request */
      400: {
        content: {
          "application/json": components["schemas"]["RsDataEmpty"];
        };
      };
    };
  };
  /** 특정 게임 테스트용 */
  getGameMapTest: {
    parameters: {
      path: {
        gameInfo: string;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "application/json": components["schemas"]["RsDataGameMapTestResponseBody"];
        };
      };
      /** @description Bad Request */
      400: {
        content: {
          "application/json": components["schemas"]["RsDataEmpty"];
        };
      };
    };
  };
  /** 행정구역 조회 */
  getAds: {
    parameters: {
      query?: {
        regionCode?: number;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "application/json": components["schemas"]["RsDataAdsResponseBody"];
        };
      };
      /** @description Bad Request */
      400: {
        content: {
          "application/json": components["schemas"]["RsDataEmpty"];
        };
      };
    };
  };
  /** 업적 목록 조회 */
  getAchievements: {
    responses: {
      /** @description OK */
      200: {
        content: {
          "application/json": components["schemas"]["RsDataGetAchievementResponseBody"];
        };
      };
      /** @description Bad Request */
      400: {
        content: {
          "application/json": components["schemas"]["RsDataEmpty"];
        };
      };
    };
  };
}
